# Generated by Django 3.2.5 on 2021-07-31 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210731_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['title'], 'verbose_name': 'Ticket'},
        ),
    ]
